### ISSUE TITLE
sentry-cli ENOENT

### ISSUE THREAD

**Issue by robbienohra** [getsentry/sentry-webpack-plugin#273]
Similar to #120 (although none of the solutions mentioned there are working for me).

```
ERROR in Sentry CLI Plugin: spawn /workspace/project/node_modules/@sentry/cli/sentry-cli ENOENT
```

I'm running a webpack build using the `node: 15` image in a GCP _Cloud Build_ job.

```
webpack --mode=production --config webpack.prod.js --env BUILD=latest
```

I only seem to see the above error with Node 15 and not with lower versions.

I have a very plain vanilla sentry webpack plugin configuration:

```
            new SentryPlugin({
                debug: true,
                ignore: ['node_modules'],
                include: [`build_latest/bundle/platform.map.js`],
                release: version + ' - ' + BUILD,
                sourceMapReference: false,
            }),
```

For the record I'm seeing the above error message at the very _end_ of the build.

**Comment by kamilogorek** [comment]
It looks like install script failure due to npm config on Docker. See: https://github.com/getsentry/sentry-cli/issues/888#issuecomment-815543425

**Comment by robbienohra** [comment]
Thanks, @kamilogorek! I've unfortunately already tried running
```
npm config set unsafe-perm true
```
(with and without a prefix to the project directory)
and still seeing the error 😢

**Comment by robbienohra** [comment]
This is the snippet from the cloud build job:

```yaml
steps:
- id: build-webpack
  waitFor: ['-']
#  name: node:14.16.1
  name: node:15.14.0
  entrypoint: bash
  args:
  - -c
  - |
    npm config set unsafe-perm true --prefix=/frontend/
    npm ci --no-progress --quiet --prefix=/frontend/
    npm run latest --prefix=/frontend/
```
